import jsPDF from 'jspdf';
import type { Answers, PolicySection } from '../types';
import { buildPolicySections } from '../policy/builder';
import { strAnswer } from '../policy/helpers';

/**
 * Client-side PDF generation using jspdf. Paginates to A4, sans-serif
 * body, manual text-wrapping via splitTextToSize (jspdf doesn't wrap
 * automatically).
 *
 * Must be called from the browser — jspdf reaches for `document` /
 * `Blob`. The Next.js entry point imports this dynamically to avoid
 * SSR issues.
 */
export function downloadPDF(answers: Answers): void {
  const sections: PolicySection[] = buildPolicySections(answers);
  const company = strAnswer(answers, 'company') || 'Company';
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const margin = 50;
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const maxW = pageW - margin * 2;
  let y = margin;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(11, 27, 58);
  const titleLines = doc.splitTextToSize(`AI Use Policy — ${company}`, maxW);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 22 + 6;

  doc.setDrawColor(11, 95, 255);
  doc.setLineWidth(2);
  doc.line(margin, y, margin + 60, y);
  y += 18;

  for (const s of sections.slice(1)) {
    // Heading
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(11, 27, 58);
    const headLines = doc.splitTextToSize(s.heading, maxW);
    if (y + headLines.length * 16 > pageH - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(headLines, margin, y);
    y += headLines.length * 16 + 6;

    // Body
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10.5);
    doc.setTextColor(31, 41, 55);
    for (const para of s.body.split('\n\n')) {
      const lines = doc.splitTextToSize(para, maxW);
      for (const ln of lines) {
        if (y + 14 > pageH - margin) {
          doc.addPage();
          y = margin;
        }
        doc.text(ln, margin, y);
        y += 14;
      }
      y += 6;
    }
    y += 8;
  }

  // Footer on the last page
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text(
    `Generated by Cloudstaff AI Policy Builder · ${new Date().toLocaleDateString()}`,
    margin,
    pageH - 24
  );

  const filename = `AI-Policy-${company.replace(/[^A-Za-z0-9]+/g, '-')}.pdf`;
  doc.save(filename);
}
